import Footer from "@/components/Footer";

import styles from './layout.module.css'

import { Inter } from 'next/font/google'
import '../app/styles/globals.css'
import Header from "@/components/header/Header";
// import '../app/styles/globals.css'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })
console.log(inter);



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// {styles.body }

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={styles.html}>
      <body className={`${styles.body} ${inter.className}`} >
        <Header/>
        <div>
          
        </div>
          {children}
       
        {/* <Footer /> */}
      </body>
    </html>
  );
}
